CREATE TABLE IF NOT EXISTS tiers (
    id                         VARCHAR(10)    NOT NULL PRIMARY KEY,
    nombre                     VARCHAR(100)   NOT NULL,
    descripcion                TEXT,
    precio_mensual             DECIMAL(10,2)  DEFAULT NULL,
    logo_mostrar               TINYINT(1)     NOT NULL DEFAULT 1,
    logo_fuentes               JSON           NOT NULL,
    portada_mostrar            TINYINT(1)     NOT NULL DEFAULT 1,
    portada_fuentes            JSON           NOT NULL,
    galeria_principal_mostrar  TINYINT(1)     NOT NULL DEFAULT 0,
    galeria_principal_fuentes  JSON           NOT NULL,
    galeria_categorias_mostrar TINYINT(1)     NOT NULL DEFAULT 0,
    galeria_categorias_fuentes JSON           NOT NULL,
    contacto_reglas            JSON           NULL,
    activo                     TINYINT(1)     NOT NULL DEFAULT 1,
    created_at                 TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO tiers
    (id, nombre, descripcion, precio_mensual,
     logo_mostrar, logo_fuentes,
     portada_mostrar, portada_fuentes,
     galeria_principal_mostrar, galeria_principal_fuentes,
     galeria_categorias_mostrar, galeria_categorias_fuentes,
     contacto_reglas,
     activo)
VALUES
('01', 'Tier 01 — Básico',
    'Ficha básica scrapeada de Google. Logo y portada desde cualquier fuente.',
    0.00,
    1, '["local","url"]',
    1, '["local","url"]',
    0, '[]',
    0, '[]',
    NULL,
    1),
('02', 'Tier 02 — Estándar',
    'Ficha con imágenes locales procesadas. Galería principal y por categorías.',
    29.00,
    1, '["local","url"]',
    1, '["local","url"]',
    1, '["local","url"]',
    1, '["local","url"]',
    NULL,
    1),
('03', 'Tier 03 — Premium',
    'Todo lo de Tier 02 más mapa Google y reseñas verificadas.',
    59.00,
    1, '["local","url"]',
    1, '["local","url"]',
    1, '["local","url"]',
    1, '["local","url"]',
    NULL,
    1);
